use freenet_stdlib::client_api::{ClientRequest, ContractRequest};
use freenet_stdlib::prelude::{ContractInstanceId, ContractKey};
use web_sys::WebSocket;

use crate::state::{
    AppEntry, ContractType, DiscoveryPhase, APP_CATALOG, CATALOG_STATE, CONTRACT_TYPES,
    DISCOVERY_PHASE, SHARDS_AVAILABLE, SHARD_STATES, TOTAL_CONTRACTS,
};
use search_common::types::{CatalogState, ShardState};

use super::node_api::send_request;

// Auto-generated by deploy-helper. Regenerate with: cargo run -p deploy-helper
const CATALOG_INSTANCE_ID: [u8; 32] = [206, 82, 64, 57, 102, 66, 218, 96, 251, 119, 231, 250, 236, 231, 29, 202, 251, 9, 67, 77, 229, 208, 16, 90, 247, 34, 102, 92, 141, 9, 117, 47];

const SHARD_INSTANCE_IDS: [[u8; 32]; 16] = [
    [97, 53, 67, 44, 50, 38, 173, 104, 58, 22, 120, 74, 160, 40, 78, 100, 244, 153, 29, 42, 207, 190, 246, 235, 160, 132, 181, 248, 190, 159, 47, 223],
    [184, 65, 62, 134, 30, 73, 64, 119, 118, 96, 47, 243, 1, 21, 227, 46, 57, 112, 13, 60, 211, 148, 31, 113, 5, 8, 243, 89, 207, 150, 11, 19],
    [15, 22, 53, 160, 148, 166, 136, 70, 168, 252, 33, 142, 249, 206, 64, 25, 79, 58, 111, 40, 12, 185, 71, 44, 111, 216, 60, 204, 105, 33, 120, 180],
    [113, 24, 158, 223, 80, 254, 171, 47, 211, 0, 125, 55, 108, 30, 65, 16, 166, 95, 196, 186, 159, 218, 2, 179, 194, 173, 44, 171, 252, 73, 74, 221],
    [72, 73, 72, 115, 5, 8, 114, 21, 114, 99, 243, 233, 216, 152, 115, 230, 155, 89, 117, 141, 82, 107, 86, 122, 50, 45, 118, 24, 153, 27, 123, 50],
    [247, 171, 121, 47, 177, 221, 95, 200, 26, 63, 85, 155, 43, 235, 131, 98, 146, 91, 157, 62, 148, 249, 144, 31, 230, 194, 40, 19, 88, 217, 199, 222],
    [148, 185, 76, 255, 66, 186, 98, 148, 187, 76, 87, 174, 199, 81, 202, 65, 173, 231, 243, 235, 117, 198, 59, 11, 9, 227, 139, 25, 54, 213, 38, 51],
    [195, 195, 235, 54, 207, 204, 182, 35, 4, 78, 162, 241, 195, 202, 252, 119, 232, 251, 44, 129, 146, 26, 10, 63, 68, 172, 75, 239, 181, 89, 186, 133],
    [100, 127, 159, 131, 211, 135, 104, 173, 131, 166, 78, 90, 37, 131, 113, 110, 145, 122, 41, 61, 220, 88, 119, 140, 169, 90, 173, 5, 210, 160, 248, 65],
    [49, 7, 182, 27, 3, 52, 37, 229, 202, 25, 182, 170, 146, 78, 141, 117, 239, 205, 99, 53, 217, 62, 246, 167, 190, 26, 117, 140, 192, 24, 23, 33],
    [195, 91, 136, 160, 108, 231, 201, 90, 97, 251, 135, 54, 94, 202, 1, 41, 68, 156, 50, 216, 248, 114, 7, 69, 210, 227, 179, 95, 86, 67, 226, 51],
    [66, 4, 253, 159, 110, 184, 166, 125, 205, 83, 65, 123, 32, 157, 89, 2, 139, 108, 187, 237, 138, 18, 130, 123, 114, 197, 8, 16, 143, 52, 40, 147],
    [12, 178, 2, 149, 120, 82, 149, 78, 230, 208, 139, 17, 172, 241, 50, 254, 46, 252, 98, 94, 69, 139, 144, 22, 69, 108, 151, 32, 242, 124, 62, 241],
    [85, 54, 47, 35, 113, 104, 178, 75, 172, 18, 76, 174, 221, 149, 170, 82, 76, 227, 29, 14, 131, 161, 72, 44, 162, 246, 71, 10, 254, 76, 101, 50],
    [102, 156, 173, 168, 6, 235, 152, 174, 152, 16, 102, 223, 124, 31, 90, 254, 135, 108, 13, 250, 133, 204, 202, 115, 36, 141, 80, 223, 238, 0, 236, 181],
    [211, 96, 196, 74, 166, 129, 123, 73, 121, 104, 209, 127, 190, 6, 112, 53, 165, 241, 38, 2, 16, 202, 92, 42, 73, 150, 119, 249, 252, 115, 82, 24],
];

fn catalog_instance_id() -> ContractInstanceId {
    ContractInstanceId::new(CATALOG_INSTANCE_ID)
}

fn shard_instance_id(shard_id: u8) -> ContractInstanceId {
    ContractInstanceId::new(SHARD_INSTANCE_IDS[shard_id as usize])
}

/// Subscribe to the catalog contract state with updates.
pub fn subscribe_catalog(ws: &WebSocket) {
    let request = ClientRequest::ContractOp(ContractRequest::Get {
        key: catalog_instance_id(),
        return_contract_code: false,
        subscribe: true,
        blocking_subscribe: false,
    });
    send_request(ws, &request);
    tracing::info!("Subscribed to catalog contract");
}

/// Subscribe to a single shard contract state with updates.
pub fn subscribe_shard(ws: &WebSocket, shard_id: u8) {
    let request = ClientRequest::ContractOp(ContractRequest::Get {
        key: shard_instance_id(shard_id),
        return_contract_code: false,
        subscribe: true,
        blocking_subscribe: false,
    });
    send_request(ws, &request);
    tracing::debug!("Subscribed to shard contract {}", shard_id);
}

/// Handle a catalog contract GET response: deserialize CBOR and update signals.
pub fn handle_catalog_response(state_bytes: &[u8]) {
    match ciborium::from_reader::<CatalogState, _>(state_bytes) {
        Ok(catalog) => {
            tracing::info!(
                "Catalog state loaded: {} entries, {} contributors",
                catalog.entries.len(),
                catalog.contributors.len()
            );
            cache_to_local_storage("catalog_state", state_bytes);
            populate_app_catalog_from_entries(&catalog);
            *CATALOG_STATE.write() = Some(catalog);
        }
        Err(e) => {
            tracing::warn!("Failed to deserialize catalog state: {}", e);
        }
    }
}

/// Handle a shard contract GET response: deserialize CBOR and update signals.
pub fn handle_shard_response(state_bytes: &[u8]) {
    match ciborium::from_reader::<ShardState, _>(state_bytes) {
        Ok(shard) => {
            let shard_id = shard.shard_id;
            let term_count = shard.index.len();
            tracing::debug!("Shard {} state loaded: {} terms", shard_id, term_count,);
            cache_to_local_storage(&format!("shard_state_{}", shard_id), state_bytes);

            let mut states = SHARD_STATES.write();
            states.insert(shard_id, shard);
            let available = states.len() as u8;
            drop(states);
            *SHARDS_AVAILABLE.write() = available;
        }
        Err(e) => {
            tracing::warn!("Failed to deserialize shard state: {}", e);
        }
    }
}

/// Populate the APP_CATALOG and CONTRACT_TYPES from catalog entries.
///
/// This replaces the old NodeDiagnostics-based discovery pipeline. The catalog
/// already contains metadata for all indexed webapps, so we populate the app
/// directory directly without issuing GET requests.
fn populate_app_catalog_from_entries(catalog: &CatalogState) {
    let mut app_catalog = APP_CATALOG.write();
    let mut contract_types = CONTRACT_TYPES.write();
    let mut new_count = 0usize;

    for (key_str, entry) in &catalog.entries {
        // Pick the best hash variant (highest total_weight) for title/description
        let best_variant = entry
            .hash_variants
            .values()
            .max_by_key(|v| v.total_weight);

        let (title, description) = match best_variant {
            Some(v) => (Some(v.title.clone()), Some(v.description.clone())),
            None => (None, None),
        };

        // Only insert/update if not already present with better data
        let app_entry = app_catalog.entry(key_str.clone()).or_insert_with(|| {
            new_count += 1;
            AppEntry {
                title: None,
                description: None,
                first_seen: entry.first_seen,
                last_seen: entry.last_seen,
                size_bytes: Some(entry.size_bytes),
                subscribers: 0,
                version: entry.version,
                publisher_key: None,
            }
        });

        // Update metadata from catalog if we have it
        if title.is_some() {
            app_entry.title = title;
        }
        if description.is_some() {
            app_entry.description = description;
        }
        app_entry.size_bytes = Some(entry.size_bytes);
        app_entry.version = entry.version;
        app_entry.last_seen = entry.last_seen;

        // Mark as WebApp in CONTRACT_TYPES (catalog entries are known webapps)
        contract_types
            .entry(key_str.clone())
            .or_insert(ContractType::WebApp);
    }

    let total = catalog.entries.len();
    drop(app_catalog);
    drop(contract_types);

    *TOTAL_CONTRACTS.write() = total;

    if new_count > 0 {
        tracing::info!(
            "Populated {} new app catalog entries from {} catalog entries",
            new_count,
            total
        );
    }

    *DISCOVERY_PHASE.write() = DiscoveryPhase::Complete;
}

/// Check if a contract key matches the catalog contract.
pub fn is_catalog_key(key: &ContractKey) -> bool {
    key.id().as_bytes() == catalog_instance_id().as_bytes()
}

/// Check if a contract key matches any shard contract, returning the shard_id.
pub fn matching_shard_id(key: &ContractKey) -> Option<u8> {
    let key_bytes = key.id().as_bytes();
    (0u8..16).find(|&shard_id| key_bytes == shard_instance_id(shard_id).as_bytes())
}

/// Get the catalog contract instance ID (for use in Update requests).
pub fn catalog_contract_key() -> ContractInstanceId {
    catalog_instance_id()
}

/// Get a shard contract instance ID (for use in Update requests).
pub fn shard_contract_key(shard_id: u8) -> ContractInstanceId {
    shard_instance_id(shard_id)
}

/// Hex fingerprint of the current catalog instance ID, used to invalidate
/// stale localStorage cache when contract IDs change across deploys.
fn contract_fingerprint() -> String {
    CATALOG_INSTANCE_ID
        .iter()
        .take(8)
        .map(|b| format!("{:02x}", b))
        .collect()
}

/// Load cached catalog and shard states from localStorage on startup.
/// Clears stale data if contract IDs have changed since last cache write.
pub fn load_cached_states() {
    // Check if cached data belongs to the current contract IDs
    let current_fp = contract_fingerprint();
    let stored_fp = load_string_from_local_storage("contract_fingerprint");
    if stored_fp.as_deref() != Some(current_fp.as_str()) {
        tracing::info!(
            "Contract IDs changed (cached={:?}, current={}), clearing stale state cache",
            stored_fp,
            current_fp
        );
        clear_contract_cache();
        return;
    }

    if let Some(bytes) = load_from_local_storage("catalog_state") {
        if let Ok(catalog) = ciborium::from_reader::<CatalogState, _>(bytes.as_slice()) {
            tracing::info!(
                "Restored cached catalog state: {} entries",
                catalog.entries.len()
            );
            *CATALOG_STATE.write() = Some(catalog);
        }
    }

    let mut available = 0u8;
    for shard_id in 0u8..16 {
        let key = format!("shard_state_{}", shard_id);
        if let Some(bytes) = load_from_local_storage(&key) {
            if let Ok(shard) = ciborium::from_reader::<ShardState, _>(bytes.as_slice()) {
                SHARD_STATES.write().insert(shard_id, shard);
                available += 1;
            }
        }
    }
    if available > 0 {
        tracing::info!("Restored {} cached shard states", available);
        *SHARDS_AVAILABLE.write() = available;
    }
}

/// Clear catalog and shard state from localStorage and in-memory signals.
pub fn clear_contract_cache() {
    if let Some(storage) = get_storage() {
        let _ = storage.remove_item("catalog_state");
        let _ = storage.remove_item("contract_fingerprint");
        for shard_id in 0u8..16 {
            let _ = storage.remove_item(&format!("shard_state_{}", shard_id));
        }
    }
    *CATALOG_STATE.write() = None;
    SHARD_STATES.write().clear();
    *SHARDS_AVAILABLE.write() = 0;
    tracing::info!("Cleared contract state cache");
}

fn cache_to_local_storage(key: &str, data: &[u8]) {
    let storage = match get_storage() {
        Some(s) => s,
        None => return,
    };
    // Encode as hex since localStorage is string-only
    let hex = data
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();
    let _ = storage.set_item(key, &hex);
    // Keep fingerprint in sync so load_cached_states can validate
    let _ = storage.set_item("contract_fingerprint", &contract_fingerprint());
}

fn load_from_local_storage(key: &str) -> Option<Vec<u8>> {
    let storage = get_storage()?;
    let hex = storage.get_item(key).ok()??;
    super::hex_decode(&hex)
}

fn load_string_from_local_storage(key: &str) -> Option<String> {
    let storage = get_storage()?;
    storage.get_item(key).ok()?
}

fn get_storage() -> Option<web_sys::Storage> {
    web_sys::window()?.local_storage().ok().flatten()
}
